### ISSUE TITLE
Terminology: actual URI

### ISSUE THREAD

**Issue by hvdsomp** [hvdsomp/signposting#1]
The term "actual URI" is used and it feels awkward. Alternatives have been proposed:
- Don't use a special term at all and just use Context IRI as per RFC5988.
-   "duty URI", "retrieving URI", "running URI", "access URI"

**Comment by zimeon** [comment]
I hadn't thought of just using "Context IRI" but in looking over the 16 places where we currently use "actual URI" it seems that in several cases we can just simplify because the current text is giving a second name to the Context URI, and in others the replacement would work with only very minor changes.

Of the other choices, I think I prefer "access URI".

**Comment by hvdsomp** [comment]
RFC5988bis, which is in last call, replaces:
- Context IRI with link source 
- Target IRI with link target. 

Since RFC5988bis will be finalized by the time we are done with our work, I will start using that terminology. In the "Terminology" section, I will briefly explain the terms.

**Comment by hvdsomp** [comment]
It turns out I really needed two terms and could not get away with just using link context. I decided to use link context and access URI. And glued them together using this sentence:

By interacting with the access URI, the user agent may discover typed links. For such links, the access URI is the link context.

**Comment by zimeon** [comment]
:+1: I think it reads fine with "access URI".

**Comment by hvdsomp** [comment]
We all seem to be OK with "access URI" after several iterations of I-D-00 so I consider this issue closed.
