### ISSUE TITLE
add rel=self & rel=api-catalog to link set?

### ISSUE THREAD

**Issue by phonedude** [hvdsomp/signposting#20]
I'm not entirely how this would work in the syntax for link sets, but there would be utility in having:

      "link":{
         "rel":"self",
         "href":"https://my.repo.org/api-info.json"
      },
      "link":{
         "rel":"api-catalog",
         "href":"https://my.repo.org/api-info.json"
      },

in the .json file

**Comment by hvdsomp** [comment]
I think the utility that you are after is that an API Catalog references itself. The API Catalog design is such that:

- there's an `anchor` member for each interoperability affordance; no other anchors are used
- only the `service-*` link relation types are used; no other link types are used

Sticking to this design approach, the following would achieve the intended utility:
- `anchor`: URL of the API Catalog, e.g. baseURL/.well-known/api-catalog
- target(s) of `service-doc` link(s): URL of API Catalog I-D, URL of API Catalog spec on signposting.org

This would also allow other well-know URI affordances to be handled in the same way.

**Comment by hvdsomp** [comment]
Added a placeholder example illustrating API Calalog entries for well-know VOID URI and well-known api-catalog.

**Comment by phonedude** [comment]
is there no way to put rels in there?  referencing the other issue, putting rel=timemap and rel=timegate would be a huge benefit.

**Comment by hvdsomp** [comment]
The API Catalog Link Set approach does not work that way. It works this way (for collection-level interop affordances):

- the context of the link (`anchor`) is the URL of the affordance
- the rel is `service-doc`, `service-desc`, or `service-metadata`
- the target of the link is the URL of documentation of the affordance

For Memento, one could handle this either in a collection-level or an item-level manner. 

A collection-level approach would be as follows for a timegate affordance (similar for timemap):
- the context of the link (`anchor`) is the baseURL for the timegate
- the `service-doc` rel is used because the link is to a human-readable spec
- the target of the link is the URL of the Memento RFC (maybe the timegate section thereof)

If one were to handle it in an item-level manner it would look as follows:
- the context of the link is a sample collection item for which Memento is supported (i.e. it exhibits `timegate` and `timemap` links)
- the `service-doc` rel is used because the link is to a human-readable spec
- the target of the link is the URL of the Memento RFC

**Comment by hvdsomp** [comment]
It looks like this can be closed.
