### ISSUE TITLE
Default response for .well-known/api-catalog

### ISSUE THREAD

**Issue by huberrob** [hvdsomp/signposting#26]
Should a request on .well-known/api-catalog immediately deliver the JSON content by default? This would avoid the extra request.

By now the spec just indicates the returned header but not the content. In [draft-ietf-httpapi-api-catalog](https://datatracker.ietf.org/doc/draft-ietf-httpapi-api-catalog/) it is defined to deliver the JSON for a _Accept: application/linkset+json_  but not if the Accept type is not defined
Is it OK to deliver the JSON by default?

Basic example: https://f-uji.net/.well-known/api-catalog (just showing the header, empty json)

**Comment by hvdsomp** [comment]
The api-catalog spec says the well-known URI should _resolve_ to the catalog document. So, that could mean directly deliver, redirect, etc. But in the end, one ends up at the actual document. Since we only define a single document format, access without mime type information should by default return the application/linkset+json.

**Comment by hvdsomp** [comment]
> 
> Basic example: https://f-uji.net/.well-known/api-catalog (just showing the header, empty json)

This should have an `api-catalog` link in the Link header ;-)

**Comment by huberrob** [comment]
still puzzling with the .htaccess  should be there now..

**Comment by hvdsomp** [comment]
@huberrob can this issue be closed? or do you have further observations?
